Add simple yaml2json script, update build-package to build providers as well, update deploy to deploy providers and start working on the API deploy strategy.

diff --git a/scripts/build-packages b/scripts/build-packages
--- a/scripts/build-packages
+++ b/scripts/build-packages
@@ -13,13 +13,15 @@
 BUILD_FOLDER='../builds'
 
 cd $(dirname $0)
-mkdir -p $BUILD_FOLDER
+mkdir -p $BUILD_FOLDER/{packages,providers}
 # Cleaning folder
 rm -rf $BUILD_FOLDER/*
+mkdir -p $BUILD_FOLDER/{packages,providers}
 
 # Fetch latest code
 git pull
 
+# Prepare packages archives
 for package in $(ls -d ../packages/*/.); do
     cd $package
     for version in $(ls -d */.); do
@@ -27,12 +29,32 @@ for package in $(ls -d ../packages/*/.); do
         PKG_FOLDER=$(dirname $package)
         PKG_NAME=$(basename $(dirname $package))
         cd "$PKG_VERSION"
-        tar cvfz ../../$BUILD_FOLDER/${PKG_NAME}_${PKG_VERSION}.tar.gz . \
+        tar cvfz ../../$BUILD_FOLDER/packages/${PKG_NAME}_${PKG_VERSION}.tar.gz . \
             > /dev/null 2>&1
         if [ $? -eq 0 ]; then
             echo "[SUCCESS] $PKG_NAME - $PKG_VERSION: package created."
         else
             echo "[ERROR] $PKG_NAME - $PKG_VERSION: package creation failed."
+        fi
+        cd ..
+    done
+    cd ..
+done
+
+# Prepare provider archives
+for provider in $(ls -d ../providers/*/.); do
+    cd $provider
+    for version in $(ls -d */.); do
+        PKG_VERSION=$(dirname $version)
+        PKG_FOLDER=$(dirname $provider)
+        PKG_NAME=$(basename $(dirname $provider))
+        cd "$PKG_VERSION"
+        tar cvfz ../../$BUILD_FOLDER/providers/${PKG_NAME}_${PKG_VERSION}.tar.gz . \
+            > /dev/null 2>&1
+        if [ $? -eq 0 ]; then
+            echo "[SUCCESS] $PKG_NAME - $PKG_VERSION: provider created."
+        else
+            echo "[ERROR] $PKG_NAME - $PKG_VERSION: provider creation failed."
         fi
         cd ..
     done
diff --git a/scripts/deploy-packages b/scripts/deploy-packages
--- a/scripts/deploy-packages
+++ b/scripts/deploy-packages
@@ -26,7 +26,7 @@ usage() {
 }
 
 setup_ansible() {
-    echo "Setting up packages for ansible"
+    echo "Setting up packages and providers for ansible"
     # Check destination folder
     if [ ! -d "$DEVOPS_ANSIBLE_ROOT" ]; then
         echo "Creating $DEVOPS_ANSIBLE_ROOT"
@@ -44,11 +44,13 @@ setup_ansible() {
         fi
     fi
 
-    for package in $(ls $PACKAGE_FOLDER/*.tar.gz); do
+    # Handle packages
+    for package in $(ls $PACKAGE_FOLDER/packages/*.tar.gz); do
         echo "Starting setup of $package"
         name=$(echo $(basename $package) | cut -f1 -d'_')
         version=$(echo ${package/.tar.gz/} | cut -f2 -d'_')
         # Checking if the package is already present
+        # Missing the check for common package .. whatever for now ..
         if [ -d "$DEVOPS_ANSIBLE_ROOT/services/$name" -a -d "$DEVOPS_ANSIBLE_ROOT/services/$name/$version" ]; then
             echo "Package $name ($version) is already present."
             echo -n "Overwrite? [y/N] "
@@ -74,6 +76,31 @@ setup_ansible() {
         tar xzf $package -C "$PACKAGE_ROOT/$version"
     done
 
+    # Handle providers
+    for provider in $(ls $PACKAGE_FOLDER/providers/*.tar.gz); do
+        echo "Starting setup of $provider"
+        name=$(echo $(basename $provider) | cut -f1 -d'_')
+        version=$(echo ${provider/.tar.gz/} | cut -f2 -d'_')
+        # Checking if the provider is already present
+        if [ -d "$DEVOPS_ANSIBLE_ROOT/providers/$name" -a -d "$DEVOPS_ANSIBLE_ROOT/providers/$name/$version" ]; then
+            echo "Provider $name ($version) is already present."
+            echo -n "Overwrite? [y/N] "
+            read overwrite
+            if [ "$overwrite" == 'y' -o "$overwrite" == 'Y' ]; then
+                # Proceed with overwrite
+                :
+            else
+                echo "Skipping..."
+                continue
+            fi
+        fi
+        mkdir -p "$DEVOPS_ANSIBLE_ROOT/providers/$name"
+        rm -rf "$DEVOPS_ANSIBLE_ROOT/providers/$name/$version"
+        mkdir -p "$DEVOPS_ANSIBLE_ROOT/providers/$name/$version"
+        # Will extract in $name/$version
+        tar xzf $provider -C "$DEVOPS_ANSIBLE_ROOT/providers/$name/$version"
+    done
+
     # Prepare the link to latest services packages
     for package in $(ls "$DEVOPS_ANSIBLE_ROOT/services/"); do
         rm -f "$DEVOPS_ANSIBLE_ROOT/services/$package/latest"
@@ -86,6 +113,14 @@ setup_ansible() {
     latest_version=$(ls "$DEVOPS_ANSIBLE_ROOT/common/" | sort | tail -1)
     echo "Latest version for common: $latest_version"
     ln -s "$latest_version" "$DEVOPS_ANSIBLE_ROOT/common/latest"
+
+    # Prepare the link to latest providers packages
+    for provider in $(ls "$DEVOPS_ANSIBLE_ROOT/providers/"); do
+        rm -f "$DEVOPS_ANSIBLE_ROOT/providers/$provider/latest"
+        latest_version=$(ls "$DEVOPS_ANSIBLE_ROOT/providers/$provider/" | sort | tail -1)
+        echo "Latest version for $provider: $latest_version"
+        ln -s "$latest_version" "$DEVOPS_ANSIBLE_ROOT/providers/$provider/latest"
+    done
 
     # Update all the PATH within the files
     # DEVOPS_PACKAGE
@@ -111,10 +146,155 @@ setup_ansible() {
             -e "s/DEVOPS_PACKAGE/$path_package/g"       \
             -e "s/DEVOPS_BASE/$path_base/g"
     done
+    # Update PATH within providers
+    cd "$DEVOPS_ANSIBLE_ROOT/providers/"
+    for provider in $(ls -d *); do
+        cd $provider
+        for version in $(ls -d * | grep -v latest); do
+            path_package=$(echo "$DEVOPS_ANSIBLE_ROOT/providers/$provider/$version" | sed -e 's/\//\\\//g')
+            path_base=$(echo "$DEVOPS_ANSIBLE_ROOT" | sed -e 's/\//\\\//g')
+            find $version -type f -print0 | xargs -0 sed -i \
+                -e "s/DEVOPS_PACKAGE/$path_package/g"       \
+                -e "s/DEVOPS_BASE/$path_base/g"
+        done
+        cd ..
+    done
 }
 
 setup_api() {
-    echo "Setting up api"
+    echo "Setting up packages and providers for api.devo.ps"
+    # Check destination folder
+    if [ ! -d "$DEVOPS_API_ROOT" ]; then
+        echo "Creating $DEVOPS_API_ROOT"
+        echo -n "Proceed? [y/N] "
+        read proceed 
+        if [ "$proceed" == 'y' -o "$proceed" == 'Y' ]; then
+            mkdir -p "$DEVOPS_API_ROOT"
+            if [ $? -ne 0 ]; then
+                echo "Error while creating $DEVOPS_API_ROOT. Aborting".
+                exit 1
+            fi
+        else
+            echo "Aborting."
+            exit
+        fi
+    fi
+
+    # Handle packages
+    for package in $(ls $PACKAGE_FOLDER/packages/*.tar.gz); do
+        echo "Starting setup of $package"
+        name=$(echo $(basename $package) | cut -f1 -d'_')
+        version=$(echo ${package/.tar.gz/} | cut -f2 -d'_')
+        # Checking if the package is already present
+        # Missing the check for common package .. whatever for now ..
+        if [ -d "$DEVOPS_API_ROOT/services/$name" -a -d "$DEVOPS_API_ROOT/services/$name/$version" ]; then
+            echo "Package $name ($version) is already present."
+            echo -n "Overwrite? [y/N] "
+            read overwrite
+            if [ "$overwrite" == 'y' -o "$overwrite" == 'Y' ]; then
+                # Proceed with overwrite
+                :
+            else
+                echo "Skipping..."
+                continue
+            fi
+        fi
+        # Proceed with setup - create folder and do cleanup
+        if [ "$name" == 'common' ]; then
+            PACKAGE_ROOT="$DEVOPS_API_ROOT/$name"
+        else
+            PACKAGE_ROOT="$DEVOPS_API_ROOT/services/$name"
+        fi
+        mkdir -p "$PACKAGE_ROOT"
+        rm -rf "$PACKAGE_ROOT/$version"
+        mkdir -p "$PACKAGE_ROOT/$version"
+        # Will extract in $name/$version
+        tar xzf $package -C "$PACKAGE_ROOT/$version"
+    done
+
+    # Handle providers
+    for provider in $(ls $PACKAGE_FOLDER/providers/*.tar.gz); do
+        echo "Starting setup of $provider"
+        name=$(echo $(basename $provider) | cut -f1 -d'_')
+        version=$(echo ${provider/.tar.gz/} | cut -f2 -d'_')
+        # Checking if the provider is already present
+        if [ -d "$DEVOPS_API_ROOT/providers/$name" -a -d "$DEVOPS_API_ROOT/providers/$name/$version" ]; then
+            echo "Provider $name ($version) is already present."
+            echo -n "Overwrite? [y/N] "
+            read overwrite
+            if [ "$overwrite" == 'y' -o "$overwrite" == 'Y' ]; then
+                # Proceed with overwrite
+                :
+            else
+                echo "Skipping..."
+                continue
+            fi
+        fi
+        mkdir -p "$DEVOPS_API_ROOT/providers/$name"
+        rm -rf "$DEVOPS_API_ROOT/providers/$name/$version"
+        mkdir -p "$DEVOPS_API_ROOT/providers/$name/$version"
+        # Will extract in $name/$version
+        tar xzf $provider -C "$DEVOPS_API_ROOT/providers/$name/$version"
+    done
+
+    # Prepare the link to latest services packages
+    for package in $(ls "$DEVOPS_API_ROOT/services/"); do
+        rm -f "$DEVOPS_API_ROOT/services/$package/latest"
+        latest_version=$(ls "$DEVOPS_API_ROOT/services/$package/" | sort | tail -1)
+        echo "Latest version for $package: $latest_version"
+        ln -s "$latest_version" "$DEVOPS_API_ROOT/services/$package/latest"
+    done
+    # Prepare the link to latest services packages
+    rm -f "$DEVOPS_API_ROOT/common/latest"
+    latest_version=$(ls "$DEVOPS_API_ROOT/common/" | sort | tail -1)
+    echo "Latest version for common: $latest_version"
+    ln -s "$latest_version" "$DEVOPS_API_ROOT/common/latest"
+
+    # Prepare the link to latest providers packages
+    for provider in $(ls "$DEVOPS_API_ROOT/providers/"); do
+        rm -f "$DEVOPS_API_ROOT/providers/$provider/latest"
+        latest_version=$(ls "$DEVOPS_API_ROOT/providers/$provider/" | sort | tail -1)
+        echo "Latest version for $provider: $latest_version"
+        ln -s "$latest_version" "$DEVOPS_API_ROOT/providers/$provider/latest"
+    done
+
+    # Update all the PATH within the files
+    # DEVOPS_PACKAGE
+    # DEVOPS_BASE
+    cd "$DEVOPS_API_ROOT/services/"
+    for package in $(ls -d *); do
+        cd $package
+        for version in $(ls -d * | grep -v latest); do
+            path_package=$(echo "$DEVOPS_API_ROOT/services/$package/$version" | sed -e 's/\//\\\//g')
+            path_base=$(echo "$DEVOPS_API_ROOT" | sed -e 's/\//\\\//g')
+            find $version -type f -print0 | xargs -0 sed -i \
+                -e "s/DEVOPS_PACKAGE/$path_package/g"       \
+                -e "s/DEVOPS_BASE/$path_base/g"
+        done
+        cd ..
+    done
+    # Update PATH within common
+    cd "$DEVOPS_API_ROOT/common"
+    for version in $(ls -d * | grep -v latest); do
+        path_package=$(echo "$DEVOPS_API_ROOT/common/$version" | sed -e 's/\//\\\//g')
+        path_base=$(echo "$DEVOPS_API_ROOT" | sed -e 's/\//\\\//g')
+        find $version -type f -print0 | xargs -0 sed -i \
+            -e "s/DEVOPS_PACKAGE/$path_package/g"       \
+            -e "s/DEVOPS_BASE/$path_base/g"
+    done
+    # Update PATH within providers
+    cd "$DEVOPS_API_ROOT/providers/"
+    for provider in $(ls -d *); do
+        cd $provider
+        for version in $(ls -d * | grep -v latest); do
+            path_package=$(echo "$DEVOPS_API_ROOT/providers/$provider/$version" | sed -e 's/\//\\\//g')
+            path_base=$(echo "$DEVOPS_API_ROOT" | sed -e 's/\//\\\//g')
+            find $version -type f -print0 | xargs -0 sed -i \
+                -e "s/DEVOPS_PACKAGE/$path_package/g"       \
+                -e "s/DEVOPS_BASE/$path_base/g"
+        done
+        cd ..
+    done    
 }
 
 # Check arguments
